
services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: aircraft
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d aircraft"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: "redis:alpine3.22"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --requirepass root

  app:
    build: .
    container_name: aircraft-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/aircraft
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata_new: